#ETC ENV setting
server:
  servlet:
    context-path: /
  port: 8090

  #db-properties:
  #  driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #  driver-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/api2?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
  #  username: api2
  #  password: api22023!@
  # HikariPool config
  #driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #maximumPoolSize: 5   # io-threads*(2-1)+1
  #cachePrepStmts: true
  #prepStmtCacheSize: 250
  #prepStmtCacheSqlLimit: 2048

crypt-key-prop:
  CRYPTO_LEGACY_KEY: CengroupAPK20!@#
  CRYPTO_LEGACY_IV: cenGroupAPV20#@!

  #jpa:
  #  show-sql: true
  #  hibernate:
  #    ddl-auto: create-drop
  #    naming:
  #      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  #      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  #properties:
  #  hibernate:
  #    dialect: org.hibernate.dialect.MySQL8Dialect

spring:
  datasource:
    url: jdbc:mysql://api2.cdjarklny1yx.ap-northeast-2.rds.amazonaws.com:3306/api2?allowMultiQueries=true&autoReconnection=true&useSSL=false&serverTimezone=Asia/Seoul
    username: api2
    password: api22023!@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5      #TODO: prod조정
      minimum-idle: 2           #TODO: prod조정
      connection-timeout: 30000 #30초
      idle-timeout: 600000      #10분
      max-lifetime: 1800000     #30분

  application:
    name: api2

  jackson:
    serialization:
      INDENT_OUTPUT: true

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  #초기개발 h2db
  #h2:
  #  console:
  #    enabled: false
  devtools:
    restart:
      enabled: true
  cloud:
    circuitbreaker:
      resilience4j:
        circuitBreaker:
          instances:
            commonCircuitBreaker:
              slidingWindowSize: 10
              permittedNumberOfCallsInHalfOpenState: 3
              slowCallRateThreshold: 50
              slowCallDurationThreshold: 5s
              minimumNumberOfCalls: 20
              waitDurationInOpenState: 1m
              failureRateThreshold: 50
              eventConsumerBufferSize: 10


jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 10Minute
  token-validity-in-seconds: 3600
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level:
    com.devops.api2: DEBUG

