#ETC ENV setting
server:
  servlet:
    context-path: /
  port: 8080

#db-properties:
#  driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#  driver-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/api2?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#  username: api2
#  password: api22023!@
  # HikariPool config
  #driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #maximumPoolSize: 5   # io-threads*(2-1)+1
  #cachePrepStmts: true
  #prepStmtCacheSize: 250
  #prepStmtCacheSqlLimit: 2048

crypt-key-prop:
  CRYPTO_LEGACY_KEY: CengroupAPK20!@#
  CRYPTO_LEGACY_IV: cenGroupAPV20#@!

#jpa:
#  show-sql: true
#  hibernate:
#    ddl-auto: create-drop
#    naming:
#      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  #properties:
  #  hibernate:
  #    dialect: org.hibernate.dialect.MySQL8Dialect

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api2?allowMultiQueries=true&autoReconnection=true&useSSL=false&serverTimezone=Asia/Seoul
    username: api2
    password: api22023!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: api2

  jackson:
    serialization:
      INDENT_OUTPUT: true

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  #h2:
  #  console:
  #    enabled: false
  devtools:
    restart:
      enabled: true
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest


jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # token is valid 10Minute
  token-validity-in-seconds: 600
  # valid 30 hours
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level:
    com.devops.api2.security: DEBUG
