#From CENTerr to Target System
spring:
  cloud:
    gateway:
      default-filters:
        - name: CustomFilter
      routes:
        - id: hydra
          uri: http://127.0.0.1:8080/ifroute/api/hydra
          predicates:
            - Path=/ifroute/api/hydra
          filters:
            - name: CustomCircuitBreaker
              args:
                name: hydraCircuitBreaker
                fallbackUri: forward:/fallbackURI


        - id: overload
          uri: http://127.0.0.1:8080/ifroute/api/overload
          predicates:
            - Path=/ifroute/api/overload
          filters:
            - name: CustomCircuitBreaker
              args:
                name: overloadCircuitBreaker
                fallbackUri: forward:/fallbackURI
        - id: ultra
          uri: http://127.0.0.1:8080/ifroute/api/ultra
          predicates:
            - Path=/ifroute/api/ultra
          filters:
            - name: CustomCircuitBreaker
              args:
                name: ultraCircuitBreaker
                fallbackUri: forward:/fallbackURI