#이게 왜있냐면.. 서킷브레이커는 비즈니스로직에 적용가능
# EX) CENTerr > (gateway > gateway(서비스로직) 포워딩) > Routelocator > CENERP
definition:
  baseUrl: http://127.0.0.1:8080
api:
  erp:
    #CENTerr > CenERP
    baseInfo: /cenerp/openapi/baseInfo
    dept: /cenerp/openapi/dept
    company: /cenerp/openapi/company
    acntinfo: /cenerp/openapi/acntinfo
    acnts-map: /cenerp/openapi/acnts-map
    ar-collects: /cenerp/openapi/ar-collects
    vendor-bonds: /cenerp/openapi/vendor-bonds
    slipinfos: /cenerp/openapi/slipinfos
    vendors: /cenerp/openapi/vendors
    vendors-charges: /cenerp/openapi/vendors-charges
    magaminfo-cenerp: /cenerp/openapi/magaminfo-cenerp
    magam-vendor-bonds: /cenerp/openapi/magam-vendor-bonds
    orderDeptMove: /cenerp/openapi/orderDeptMove
    dirct_persexp: /cenerp/openapi/dirct_persexp
    dept-acnt-info: /cenerp/openapi/dept-acnt-info
    magaminfo-final-cenerp: /cenerp/openapi/magaminfo-final-cenerp
    project-amt-info: /cenerp/openapi/project-amt-info
    magam-pl-bonds: /cenerp/openapi/magam-pl-bonds
    hometax-status: /cenerp/openapi/hometax-status
    cost-project-info: /cenerp/openapi/cost-project-info
    dept_persexp: /cenerp/openapi/dept_persexp
    exchrate_info: /cenerp/openapi/exchrate_info
    slipinfos-post: /cenerp/openapi/slipinfos-post #POST
    reverse-taxes-post: /cenerp/openapi/reverse-taxes-post #POST
    contUsers-do: /api/contUsers.do
    order_info: /cenerp/openapi/order_info

    #Groupware 인사연동
    dept_itcgw: /cenerp/openapi/dept_itcgw
    user_itcgw: /cenerp/openapi/user_itcgw
    title_itcgw: /cenerp/openapi/title_itcgw

    #secucen HR연동
    dept_secucen: /cenerp/openapi/dept_secucen
    baseinfo_secucen: /cenerp/openapi/baseinfo_secucen
    order_mm: /cenerp/openapi/order_mm
    order_info: /cenerp/openapi/order_info

    #pr > CenERP
    magaminfo-cenpcs: /cenerp/openapi/magaminfo-cenpcs
    taxes: /cenerp/openapi/taxes
    reverse-taxes: /cenerp/openapi/reverse-taxes

  pr:
    #CenERP > PR
    getVendorBuyerInfo: /interface/getVendorBuyerInfo.so
    getVendorNomalInfo: /interface/getVendorNomalInfo.so
    getVendorManagerInfo: /interface/getVendorManagerInfo.so
    getContractInfo: /interface/getContractInfo.so
    getContractMonthlyPayInfo: /interface/getContractMonthlyPayInfo.so
    getFIPurchaseCost: /interface/getFIPurchaseCost.so
    getBusinessIncomePayConfirmInfo: /interface/getBusinessIncomePayConfirmInfo.so
    doBusinessIncomePayConfirm: /interface/doBusinessIncomePayConfirm.so #POST Array BodyParam

    #CENTerr > PR
    projectSave: /interface/projectSave.so #POST Array BodyParam
    getItemTaxonomyInfo: /interface/getItemTaxonomyInfo.so
    getItemStandardInfo: /interface/getItemStandardInfo.so
    cpResult: /interface/cpResult.so #POST Array BodyParam
    giResult: /interface/giResult.so #POST Array BodyParam
    getContractInfoCENTerr: /interface/centerr/getContractInfo.so
    getContractMonthlyPayPlan: /interface/centerr/getContractMonthlyPayPlan.so