#이게 왜있냐면.. 서킷브레이커는 비즈니스로직에 적용가능
# EX) CENTerr > (gateway > gateway(서비스로직) 포워딩) > Routelocator > CENERP
definition:
  baseUrl: http://127.0.0.1:8080
api:
  erp:
    #CENTerr > CenERP
    baseInfo: /cenerp/openapi/baseInfo
    dept: /cenerp/openapi/dept
    company: /cenerp/openapi/company
    acntinfo: /cenerp/openapi/acntinfo
    acnts-map: /cenerp/openapi/acnts-map
    ar-collects: /cenerp/openapi/ar-collects
    vendor-bonds: /cenerp/openapi/vendor-bonds
    slipinfos: /cenerp/openapi/slipinfos
    vendors: /cenerp/openapi/vendors
    vendors-charges: /cenerp/openapi/vendors-charges
    magaminfo-cenerp: /cenerp/openapi/magaminfo-cenerp
    magam-vendor-bonds: /cenerp/openapi/magam-vendor-bonds
    orderDeptMove: /cenerp/openapi/orderDeptMove
    dirct_persexp: /cenerp/openapi/dirct_persexp
    dept-acnt-info: /cenerp/openapi/dept-acnt-info
    magaminfo-final-cenerp: /cenerp/openapi/magaminfo-final-cenerp
    project-amt-info: /cenerp/openapi/project-amt-info
    magam-pl-bonds: /cenerp/openapi/magam-pl-bonds
    hometax-status: /cenerp/openapi/hometax-status
    cost-project-info: /cenerp/openapi/cost-project-info
    dept_persexp: /cenerp/openapi/dept_persexp
    exchrate_info: /cenerp/openapi/exchrate_info
    slipinfos-post: /cenerp/openapi/slipinfos-post #POST
    reverse-taxes-post: /cenerp/openapi/reverse-taxes-post #POST
    contUsers-do: /api/contUsers.do

    #pr > CenERP
    magaminfo-cenpcs: /cenerp/openapi/magaminfo-cenpcs
    taxes: /cenerp/openapi/taxes
    reverse-taxes: /cenerp/openapi/reverse-taxes

  pr:
    #CenERP > PR
    getVendorBuyerInfo-so: /interface/getVendorBuyerInfo.so
    getVendorNomalInfo-so: /interface/getVendorNomalInfo.so
    getVendorManagerInfo-so: /interface/getVendorManagerInfo.so
    getContractInfo-so: /interface/getContractInfo.so
    getContractMonthlyPayInfo-so: /interface/getContractMonthlyPayInfo.so
    getFIPurchaseCost-so: /interface/getFIPurchaseCost.so
    getBusinessIncomePayConfirmInfo-so: /interface/getBusinessIncomePayConfirmInfo.so
    doBusinessIncomePayConfirm-so: /interface/doBusinessIncomePayConfirm.so #POST

    #CENTerr > PR
    projectSave-so: /interface/projectSave.so #POST
    getItemTaxonomyInfo-so: /interface/getItemTaxonomyInfo.so
    getItemStandardInfo-so: /interface/getItemStandardInfo.so
    #getContractInfo-so: /interface/centerr/getContractInfo.so